.TH SYSTEM-CONFIG-LANGUAGE 1 "June 04, 2013"
.SH NAME
\fBsystem-config-language\fR\ -  A graphical interface for modifying the system language.
.SH DESCRIPTION
.PP
   This tool will allow user to add language support. When used to add support for
any language, this tool will use yum and install the required packages to use
desktop in your preferred language. This will also change the locale of the
root user only.

This project is available at http://fedorahosted.org/system-config-language


.PP
.SH AUTHOR
Parag Nemade <pnemade@fedoraproject.org>
.PP
